[default_session]
startup_command = "ls"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "tmux"
path = "~/.config/tmux"

[[session]]
name = "nvim"
path = "~/.config/nvim"

[[session]]
name = "hypr"
path = "~/.config/hypr"

[[session]]
name = "waybar"
path = "~/.config/waybar"

[[session]]
name = "yadm"
path = "~/.config/yadm"

[[session]]
name = "user systemd"
path = "~/.config/systemd/user"
