[tools]
go = "latest"
krew = "latest"
kubectl = "latest"
kubectx = "latest"
kubens = "latest"
yarn = "latest"
php = "latest"
ruby = "latest"
node = "lts"
bun = "latest"
usage = "latest"
doggo = "latest"
helm = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
